---
- name: Download soracom setup tool
  get_url:
    url: https://soracom-files.s3.amazonaws.com/setup_air.sh
    dest: /tmp/setup_air.sh
    force: true

- name: Setup soracom air
  become: true
  shell: >
    /bin/bash /tmp/setup_air.sh
- name: Delete /tmp/setup_air.sh
  become: true
  file:
    path: /tmp/setup_air.sh
    state: absent
