---
- name: Install dnsmasq
  become: true
  apt:
    update_cache: yes
    name: dnsmasq

- name: enable dnsmasq
  become: true
  service:
    name: dnsmasq
    enabled: yes

- name: Copy dnsmasq.conf
  become: true
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
