---
- name: Install iptables
  become: true
  apt:
    update_cache: yes
    name: iptables

- name: Set sysctl net.ipv4.ip_forward
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-router.conf

- name: Set masquerade
  become: true
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: ppp0

- name: Save iptables
  become: true
  shell: |
    iptables-save > /etc/iptables.ipv4.nat

- name: Set restore process iptables
  become: true
  lineinfile:
    path: /etc/rc.local
    line: "iptables-restore < /etc/iptables.ipv4.nat"
    insertbefore: "exit 0"
